run:
  timeout: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - golint
    - govet
    - errcheck
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - goconst
    - gosec
    - goimports
    - megacheck

issues:
  exclude-use-default: false
  exclude:
    - G104
    - G204
    - should have a package comment, unless it's in another file for this package
